"""Initial tables

Revision ID: 7e6e88dc2099
Revises: 
Create Date: 2025-09-04 19:24:54.416782

"""
from alembic import op
import sqlalchemy as sa


revision = '7e6e88dc2099'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ##